### ISSUE TITLE
Installation via homebrew

### ISSUE THREAD

**Issue by johanhaleby** [chmouel/kss#2]
Describe the feature request

Kss should be installable via brew.

Describe alternatives you've considered

I can't really think of any :)

**Comment by chmouel** [comment]
Done! https://github.com/chmouel/kss/#homebrew

**Comment by johanhaleby** [comment]
@chmouel Awesome! However when I try to run `kss <pod>` after having done a fresh install from brew I run into this error:

```
$ kss mypod
/bin/sh: fzf: command not found
No pods is no news which is arguably no worries. 🤷🏼‍♂️🤷🏻‍♀️
```

**Comment by johanhaleby** [comment]
I think that fzf should be added as a transitive dependency when installing kss via brew

**Comment by johanhaleby** [comment]
After having run `brew install fzf` manually everything seems to work

**Comment by chmouel** [comment]
Yep! I forgot about those, I just added them in https://github.com/chmouel/homebrew-kss/commit/faa9b160fce006e9c350a9cdb0279bfe804476f3, you should be able to `brew reinstall` unless you don't need it :)
