### ISSUE TITLE
kss should "respect" the user's colors

### ISSUE THREAD

**Issue by vdemeester** [chmouel/kss#4]
**Is your feature request related to a problem? Please describe.**
Currently `kss` display the name of the container in a hard `black` colors. 
![image](https://user-images.githubusercontent.com/6508/70136091-a0aa4500-168b-11ea-9339-c15b6c6beb1b.png)

**Describe the solution you'd like**
I would like it to use the user's color (aka here no hard black, just standard background color)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chmouel** [comment]
should work now, i.e: 

![image](https://user-images.githubusercontent.com/98980/70147560-d0b21200-16a4-11ea-855e-c7273ba02d00.png)

**Comment by vdemeester** [comment]
:tada:
